Resolve favicon path, https://github.com/luckyframework/lucky/issues/473

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -3,37 +3,42 @@
 # Exit if any subcommand fails
 set -e
 
-if ! command -v yarn > /dev/null; then
-  printf 'Yarn is not installed.\n'
-  printf 'See https://yarnpkg.com/lang/en/docs/install/ for install instructions.\n'
-  exit 1
-fi
-
-if ! command -v heroku > /dev/null; then
-  printf 'Heroku CLI is not installed.\n'
-  printf 'See https://devcenter.heroku.com/articles/heroku-cli for install instructions.\n'
-  exit 1
-fi
-
 indent() {
   while read LINE; do
     echo "  $LINE" || true
   done
 }
 
-echo "\n▸ Installing node dependencies"
-yarn install | indent
+if ! command -v yarn > /dev/null; then
+  printf 'Yarn is not installed.\n'
+  printf 'See https://yarnpkg.com/lang/en/docs/install/ for install instructions.\n'
+  exit 1
+fi
 
-echo "\n▸ Compiling assets"
-bin/compile_assets build | indent
+echo -e "\n▸ Installing node dependencies"
+yarn install --silent | indent
 
-echo "\n▸ Installing shards"
+echo -e "\n▸ Compiling assets"
+yarn dev | indent
+
+echo -e "\n▸ Installing shards"
 crystal deps | indent
 
-echo "\n▸ Setting up the database"
+echo -e "\n▸ Checking that a process runner is installed"
+# Only if this isn't CI
+if [ -z "$CI" ]; then
+  lucky ensure_process_runner_installed
+fi
+echo "✔ Done" | indent
+
+echo -e "\n▸ Setting up the database"
 lucky db.create | indent
 
-echo "\n▸ Migrating the database"
+echo -e "\n▸ Migrating the database"
 lucky db.migrate | indent
 
-echo "\n▸ All done. Run 'lucky dev' to start the app"
+echo -e "\n▸ Seed the database with required and sample records"
+lucky db.required_seeds | indent
+lucky db.helpful_seeds | indent
+
+echo -e "\n✔ All done. Run 'lucky dev' to start the app"
